import { EMPTY_REFORMS } from './constants';
import type { RegistrationCase } from './types';

export function createEmptyRegistrationCase(options: {
  id: string;
  userId: string | null;
  mode?: RegistrationCase['mode'];
  now?: string;
}): RegistrationCase {
  const now = options.now ?? new Date().toISOString();
  return {
    id: options.id,
    userId: options.userId,
    mode: options.mode ?? 'case',
    title: 'Nuevo expediente',
    status: 'draft',
    processStage: 'not-purchased',
    operation: 'purchase',
    sellerType: 'unknown',
    sellerCountry: null,
    purchasePrice: null,
    purchaseCurrency: 'EUR',
    purchaseDate: null,
    invoiceVatNumber: null,
    invoiceVatScheme: null,
    buyerType: 'individual',
    autonomousCommunity: null,
    municipality: null,
    taxableBase: null,
    marketValue: null,
    registrationTaxSubjectConfirmed: null,
    taxBenefitKind: 'unknown',
    taxBenefitRequiresPriorRecognition: null,
    n1EconomicUseConfirmed: null,
    n1VatDeductionPercent: null,
    customsUnionStatusConfirmed: null,
    northernIrelandV5cConfirmed: null,
    relocationDates: {
      previousResidenceFrom: null,
      spanishResidenceFrom: null,
      ownershipFrom: null,
      useFrom: null,
    },
    firstEntryIntoSpainDate: null,
    firstEntryIntoEuDate: null,
    relocationNormalTaxationConfirmed: null,
    relocationRegistrationDeadlineConfirmed: null,
    relocationNonTransferAcknowledged: false,
    fiscalHorsepower: null,
    ivtmDate: null,
    municipalBenefitKind: 'unknown',
    ivtmStatus: 'pending',
    specialCircumstances: [],
    vehicle: {
      brand: '',
      model: '',
      vin: '',
      firstRegistrationDate: null,
      mileageKm: null,
      category: 'UNKNOWN',
      fuel: null,
      co2GKm: null,
      co2Source: 'unknown',
      co2Verified: false,
      engineCc: null,
      powerKw: null,
      massKg: null,
      seats: null,
      registrationCountry: '',
      manufacturingCountry: null,
      foreignRegistration: null,
      previouslyRegisteredAbroad: true,
      exportDeregistered: null,
      transportMethod: 'unknown',
      fieldK: null,
      approvalNumber: null,
      cocAvailable: null,
      cocValidityConfirmed: false,
      cocVinMatchConfirmed: false,
      foreignTechnicalDocumentAvailable: null,
      foreignInspectionCertificateAvailable: null,
      foreignInspectionDate: null,
      foreignInspectionValidUntil: null,
      approvalType: 'unknown',
      reforms: { ...EMPTY_REFORMS },
      previouslyRegisteredInSpain: false,
      categoryConfirmedOnSpanishItv: false,
    },
    createdAt: now,
    updatedAt: now,
    deletedAt: null,
  };
}
