import type { RegistrationCase } from './types';

export const PRACTICE_REGISTRATION_CASE: RegistrationCase = {
  id: '00000000-0000-4000-8000-000000000001',
  userId: null,
  mode: 'practice',
  title: 'Práctica ficticia · turismo usado de Alemania',
  status: 'in-progress',
  processStage: 'purchased',
  operation: 'purchase',
  sellerType: 'private',
  sellerCountry: 'DE',
  purchasePrice: 18_500,
  purchaseCurrency: 'EUR',
  purchaseDate: '2026-07-15',
  invoiceVatNumber: null,
  invoiceVatScheme: null,
  buyerType: 'individual',
  autonomousCommunity: 'madrid',
  municipality: 'Madrid',
  taxableBase: 16_200,
  marketValue: 17_000,
  registrationTaxSubjectConfirmed: true,
  taxBenefitKind: 'none',
  taxBenefitRequiresPriorRecognition: false,
  n1EconomicUseConfirmed: null,
  n1VatDeductionPercent: null,
  customsUnionStatusConfirmed: null,
  northernIrelandV5cConfirmed: null,
  relocationDates: {
    previousResidenceFrom: null,
    spanishResidenceFrom: null,
    ownershipFrom: null,
    useFrom: null,
  },
  firstEntryIntoSpainDate: '2026-07-20',
  firstEntryIntoEuDate: '2026-07-20',
  relocationNormalTaxationConfirmed: null,
  relocationRegistrationDeadlineConfirmed: null,
  relocationNonTransferAcknowledged: false,
  fiscalHorsepower: 12.6,
  ivtmDate: '2026-08-05',
  municipalBenefitKind: 'none',
  ivtmStatus: 'requested',
  specialCircumstances: [],
  vehicle: {
    brand: 'Volkswagen',
    model: 'Golf 2.0 TDI',
    vin: 'WVWZZZ1KZBW000001',
    firstRegistrationDate: '2020-04-15',
    mileageKm: 82_400,
    category: 'M1',
    fuel: 'Diésel',
    co2GKm: 132,
    co2Source: 'coc',
    co2Verified: true,
    engineCc: 1968,
    powerKw: 110,
    massKg: 1480,
    seats: 5,
    registrationCountry: 'DE',
    manufacturingCountry: 'DE',
    foreignRegistration: 'B-MP 2026',
    previouslyRegisteredAbroad: true,
    exportDeregistered: true,
    transportMethod: 'carrier',
    fieldK: 'e1*2007/46*0000*00',
    approvalNumber: 'e1*2007/46*0000*00',
    cocAvailable: true,
    cocValidityConfirmed: true,
    cocVinMatchConfirmed: true,
    foreignTechnicalDocumentAvailable: true,
    foreignInspectionCertificateAvailable: true,
    foreignInspectionDate: '2025-11-10',
    foreignInspectionValidUntil: '2027-11-10',
    approvalType: 'eu-type',
    reforms: {
      suspension: false,
      nonEquivalentWheels: false,
      spacers: false,
      lighting: false,
      towBar: false,
      seats: false,
      classification: false,
      bodywork: false,
      camperConversion: false,
      exhaust: false,
      powerOrEngine: false,
      dimensions: false,
      exteriorElements: false,
      steeringConversion: false,
      structural: false,
    },
    previouslyRegisteredInSpain: false,
    categoryConfirmedOnSpanishItv: false,
  },
  createdAt: '2026-07-15T10:00:00.000Z',
  updatedAt: '2026-08-05T10:00:00.000Z',
  deletedAt: null,
};
