import { randomBytes } from 'node:crypto';
import { NextResponse, type NextRequest } from 'next/server';
import {
  emailAuthFlow,
  emailOtpDestination,
  isEmailOtpTokenHash,
  parseEmailOtpType,
  type EmailAuthFlow,
} from '@/lib/auth/email-otp';
import {
  RECOVERY_AUTHORIZED_COOKIE,
  RECOVERY_STATE_COOKIE,
  recoveryCookieOptions,
  recoveryTokensMatch,
} from '@/lib/auth/recovery-flow';
import { safeInternalPath } from '@/lib/auth/redirect';
import { createSupabaseServerClient } from '@/lib/supabase/server';

export const dynamic = 'force-dynamic';

type ConfirmationFailure = 'expired' | 'invalid' | 'provider';

export async function GET(request: NextRequest) {
  const tokenHash = request.nextUrl.searchParams.get('token_hash');
  const requestedType = request.nextUrl.searchParams.get('type');
  const otpType = parseEmailOtpType(requestedType);
  const flow = emailAuthFlow(requestedType);
  const next = otpType
    ? emailOtpDestination(otpType, request.nextUrl.searchParams.get('next'))
    : safeInternalPath(request.nextUrl.searchParams.get('next'));
  const recoveryState = request.nextUrl.searchParams.get('state');
  const recoveryStateCookie = request.cookies.get(RECOVERY_STATE_COOKIE)?.value;
  const providerError = request.nextUrl.searchParams.get('error');
  const providerErrorCode = request.nextUrl.searchParams.get('error_code');
  const providerErrorDescription = request.nextUrl.searchParams.get('error_description');
  const providerFailure = providerError || providerErrorCode
    ? classifyFailure(providerErrorCode, providerErrorDescription ?? providerError)
    : null;

  // The state is an additional browser-binding check for links generated by
  // /api/auth/recover. Direct token_hash templates do not carry it, so the
  // single-use Supabase token remains the authority when state is absent.
  if (
    flow === 'recovery'
    && recoveryState
    && !recoveryTokensMatch(recoveryState, recoveryStateCookie)
  ) {
    return failure(request, next, 'invalid', 'recovery');
  }

  try {
    const supabase = await createSupabaseServerClient();

    if (providerFailure) {
      return failure(request, next, providerFailure, flow);
    }

    if (!otpType || !isEmailOtpTokenHash(tokenHash)) {
      return failure(request, next, 'invalid', flow);
    }

    const { data: verification, error: verificationError } = await supabase.auth.verifyOtp({
      token_hash: tokenHash,
      type: otpType,
    });
    if (verificationError) {
      return failure(
        request,
        next,
        classifyFailure(verificationError.code, verificationError.message),
        flow,
      );
    }

    // verifyOtp writes the SSR session through the server client's cookie
    // adapter. getUser then verifies that issued session with Supabase.
    const { data, error: userError } = await supabase.auth.getUser();
    if (
      userError
      || !data.user
      || !verification.user
      || verification.user.id !== data.user.id
    ) {
      return failure(request, next, 'invalid', flow);
    }

    const response = NextResponse.redirect(new URL(next, request.nextUrl.origin));
    if (flow === 'recovery') {
      response.cookies.set(
        RECOVERY_AUTHORIZED_COOKIE,
        randomBytes(32).toString('base64url'),
        recoveryCookieOptions(10 * 60),
      );
      response.cookies.set(RECOVERY_STATE_COOKIE, '', recoveryCookieOptions(0));
    }
    return response;
  } catch {
    return failure(request, next, 'provider', flow);
  }
}

function classifyFailure(
  code: string | undefined | null,
  description: string | undefined | null,
): ConfirmationFailure {
  const material = `${code ?? ''} ${description ?? ''}`.toLowerCase();
  if (/expired|expiry|otp_expired/.test(material)) return 'expired';
  if (/invalid|used|verifier|token|code/.test(material)) return 'invalid';
  return 'provider';
}

function failure(
  request: NextRequest,
  next: string,
  status: ConfirmationFailure,
  flow: EmailAuthFlow,
) {
  const destination = new URL('/auth/confirm', request.nextUrl.origin);
  destination.searchParams.set('status', status);
  destination.searchParams.set('next', next);
  destination.searchParams.set('flow', flow);
  const response = NextResponse.redirect(destination);
  if (flow === 'recovery') {
    response.cookies.set(RECOVERY_STATE_COOKIE, '', recoveryCookieOptions(0));
    response.cookies.set(RECOVERY_AUTHORIZED_COOKIE, '', recoveryCookieOptions(0));
  }
  return response;
}
